#!/usr/bin/env python3
"""
Optional ML trainer for exported feature vectors.

Input CSV requirements:
- One row per analyzed binary.
- Feature columns generated by the app.
- A target column named "label".

Example:
    python train_model.py dataset.csv
"""

from __future__ import annotations

import sys
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


DROP_COLUMNS = {"filename", "sha256", "md5", "sample_name"}


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: python train_model.py dataset.csv")
        return 1

    dataset_path = Path(sys.argv[1])
    if not dataset_path.exists():
        print(f"Dataset not found: {dataset_path}")
        return 1

    df = pd.read_csv(dataset_path)

    if "label" not in df.columns:
        print("Dataset must contain a 'label' column.")
        return 1

    y = df["label"]
    X = df.drop(columns=["label"])

    for col in list(X.columns):
        if col in DROP_COLUMNS:
            X = X.drop(columns=[col])

    X = X.select_dtypes(include=["number", "bool"]).fillna(0)

    if len(df) < 10:
        print("Warning: very small dataset. The trained model will not generalize well.")

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=42,
        stratify=y if y.nunique() > 1 else None,
    )

    model = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", RandomForestClassifier(
            n_estimators=300,
            random_state=42,
            class_weight="balanced",
            max_depth=None,
        )),
    ])

    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    print(classification_report(y_test, predictions))

    bundle = {
        "model": model,
        "feature_columns": list(X.columns),
    }
    joblib.dump(bundle, "obfuscation_model.joblib")
    print("Saved model to obfuscation_model.joblib")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
